- hosts: raijin.nci.org.au

  vars:
    - source_dir: /g/data/xe2/opt/new/source
    - soft_dir: /g/data/xe2/opt/new/software
    - modules_dir: /g/data/xe2/opt/new/modules
    - module_template: "raijin-module.j2"
    - clean_source: true
    - host_build_script: ""
    - global_dev_modules:
      - gcc/4.9.0
      - python/2.7.11
      - intel-cc/17.0.1.132
      - intel-fc/17.0.1.132
      - intel-ipp/17.0.1.132
      - intel-mkl/17.0.1.132
      - intel-tbb/17.0.1.132
      - cmake/3.8.2
      - yasm
      - autoconf
      - autotools
      - zlib
      - bzip2
      - xz

  tasks:
    - import_tasks: tasks/libraries.yml
    - import_tasks: tasks/utils.yml
    - import_tasks: tasks/bioinf.yml
    - import_tasks: tasks/nanopore.yml
    - import_tasks: tasks/popgen.yml
    - import_tasks: tasks/phenomics.yml
