- hosts: all

  vars:
    - source_dir: /g/data/xe2/opt/new/source
    - soft_dir: /g/data/xe2/opt/new/software
    - modules_dir: /g/data/xe2/opt/new/modules
    - clean_source: false
    - host_build_script: >
      export NCI_GXX_ABI_WARNING=1
    - global_dev_modules:
      - gcc/5.2.0
      - python/2.7.11
      - intel-cc/17.0.0.098
      - intel-fc/17.0.0.098
      - intel-ipp/17.0.0.098
      - intel-mkl/17.0.0.098
      - intel-tbb/17.0.0.098
      - cmake/3.8.2

  tasks:
    - name: "Create directories"
      file:
        dest: "{{item}}"
        state: directory
        mode: 0775
      with_items:
        - "{{source_dir}}"
        - "{{soft_dir}}"
        - "{{modules_dir}}"

    ####################
    #  AdapterRemoval  #
    ####################
    - include: tasks/software_module.yml
      vars:
        name: adapterremoval
        version: "2.2.1a"
        url: "https://github.com/MikkelSchubert/adapterremoval/archive/v{{version}}.tar.gz"
        required_modules:
          - "zlib/1.2.8"
          - "bzip2/1.0.6"
        unpack_creates: Makefile
        build_script: >
          export CC=gcc &&
          export CXX=g++ &&
          make &&
          make install PREFIX="{{ soft_dir }}/{{name}}-{{version}}"
        build_creates: bin/AdapterRemoval
        module_def:
          help_text: 'rapid adapter trimming, identification, and read merging'
          dev: false
      tags: modules,adapterremoval

    #########
    #  Axe  #
    #########
    - include: tasks/software_module.yml
      vars:
        name: axe
        version: "0.3.2"
        url: "https://github.com/kdmurray91/axe/archive/{{version}}.tar.gz"
        required_modules:
          - "zlib/1.2.8"
        unpack_creates: CMakeLists.txt
        build_script: >
          rm -rf build && mkdir build && cd build &&
          cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DZLIB_ROOT=$ZLIB_ROOT .. &&
          make &&
          make test &&
          make install 
        build_creates: bin/axe-demux
        module_def:
          help_text: 'rapid demultiplexer'
          dev: false
      tags: modules,axe


    ############
    #  Beagle  #
    ############
    - include: tasks/software_module.yml
      vars:
        name: beagle
        version: "4.1-08Jun17"
        url: http://faculty.washington.edu/browning/beagle/beagle.08Jun17.d8b.jar
        required_modules:
          - "java/jdk1.8.0_60"
        build_script: >
          cp {{source_dir}}/{{name}}-{{version}}/beagle*.jar "$PREFIX/{{build_creates}}"
        build_creates: "beagle.jar"
        module_def:
          help_text: 'Genotype calling and  imputation'
          dev: false
        java_wrapper:
          jar: "{{soft_dir}}/{{name}}-{{version}}/{{build_creates}}"
          mem: "31g"
      tags: modules,beagle

    #########
    #  BWA  #
    #########
    - include: tasks/software_module.yml
      vars:
        name: bwa
        version: "0.7.15"
        url: "https://github.com/lh3/bwa/archive/v{{version}}.tar.gz"
        required_modules:
          - "zlib/1.2.8"
        unpack_creates: Makefile
        build_script: >
          make &&
          mkdir -p "$PREFIX/bin" "$PREFIX/share/man/man1" &&
          cp bwa "$PREFIX/bin/" &&
          cp bwa.1 "$PREFIX/share/man/man1/"
        build_creates: bin/bwa
        module_def:
          help_text: 'the Burrows-wheeler short read aligner'
          dev: false
      tags: modules,bwa

    ############
    #  Pindel  #
    ############
    - include: tasks/software_module.yml
      vars:
        name: pindel
        version: "0.2.5b8"
        url: "https://github.com/genome/pindel/archive/v{{version}}.tar.gz"
        required_modules:
          - "htslib/1.4"
          - "zlib/1.2.8"
        unpack_creates: INSTALL
        build_script: >
          curl https://patch-diff.githubusercontent.com/raw/genome/pindel/pull/59.patch | patch -p1 &&
          bash ./INSTALL $HTSLIB_ROOT &&
          mkdir -p $PREFIX/bin &&
          cp pindel pindel2vcf sam2pindel pindel2vcf4tcga $PREFIX/bin/
        build_creates: bin/pindel
        module_def:
          help_text: 'the pindel SV caller'
          dev: false
      tags: modules,pindel
