- hosts: all

  vars:
    - source_dir: /g/data/xe2/opt/new/source
    - soft_dir: /g/data/xe2/opt/new/software
    - modules_dir: /g/data/xe2/opt/new/modules
    - module_template: "raijin-module.j2"
    - clean_source: false
    - host_build_script: >
        export NCI_GXX_ABI_WARNING=1
    - global_dev_modules:
      - gcc/5.2.0
      - python/2.7.11
      - intel-cc/17.0.1.132
      - intel-fc/17.0.1.132
      - intel-ipp/17.0.1.132
      - intel-mkl/17.0.1.132
      - intel-tbb/17.0.1.132
      - cmake/3.8.2

  tasks:
    - import_tasks: tasks/bioinf.yml
